### ISSUE TITLE
AbstractMethodError when using JSON log encoder

### ISSUE THREAD

**Issue by thumbtack-eee** [thumbtack/becquerel#2]
Specifically `java.lang.AbstractMethodError: net.logstash.logback.encoder.LogstashEncoder.headerBytes()[B`. Upgrading `"net.logstash.logback" % "logstash-logback-encoder"` from 4.8 to 4.11 fixes this issue.

**Comment by stleary** [comment]
Thanks! Spent 2 days trying to figure out why logback was crashing with this error. Upgrading logstash to 4.11 fixed the problem.
